---
- name: "Update and upgrade apt packages"
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: "Install common security packages (Fail2Ban)"
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: "Ensure Fail2Ban service is running and enabled"
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes